### ISSUE TITLE
Missing GUI element on Ubuntu (flatpak version) ?

### ISSUE THREAD

**Issue by fredOnGitHub** [dune3d/dune3d#127]
Hello,

How Can I began ?
![aa](https://github.com/user-attachments/assets/72f98ad3-a14c-4cee-a050-08c217660543)

There isn't example on Youtube.

I chose Flatpak version because it is too hard from command line (dependency...)
 
Thanks

**Comment by carrotIndustries** [comment]
> There isn't example on Youtube.

See the tutorial: https://docs.dune3d.org/en/latest/simple-part.html

**Comment by fredOnGitHub** [comment]
Thank You. I did the example. It was simpler with my Solvespace experience. 
I liked Chamfer.
I have seen here : https://github.com/solvespace/solvespace/issues/577 that OpenCascade has poor quality codebase.
In my case (the example) it was without problems
