### ISSUE TITLE
Problem starting program on Linux

### ISSUE THREAD

**Issue by ansie3045** [dune3d/dune3d#128]
I'm running Arch Linux with Plasma

Trying running with Flatpak: 

flatpak run org.dune3d.dune3d
 
[error1.txt](https://github.com/user-attachments/files/16644625/error1.txt)

 

Try running with AUR:

dune3d
[error2.txt](https://github.com/user-attachments/files/16644626/error2.txt)

**Comment by carrotIndustries** [comment]
Nvidida GPU by any chance? Seems to be a duplicate of #87

**Comment by ansie3045** [comment]
Yes, you are right...
