### ISSUE TITLE
Dependency "OpenCASCADE" not found

### ISSUE THREAD

**Issue by oleka2** [dune3d/dune3d#129]
I've just tried to compile Dune 3D, on my Slackware Linux 64, but my opencascade was not recognized properly.

```
Run-time dependency opencascade found: NO (tried cmake)
meson.build:19:14: ERROR: Dependency "OpenCASCADE" not found, tried cmake
```

I had the same problem with Horizon-eda a couple of years ago. 
Appending -lTKG3d to the LDFLAGS_OCE variable in the Makefile helped in this matter.

**Comment by carrotIndustries** [comment]
Never used slackware before Ran the `ghcr.io/aclemons/slackware:15.0` container to try and get a working slackware setup. Installed git and tried to clone the repo and got stuck at `fatal: unable to access 'https://github.com/dune3d/dune3d/': SSL certificate problem: unable to get local issuer certificate
`

Can you give detailed instruction how to get from that empty container image to where you got stuck at building dune3d?

Depending on where opencascade is installed, (doesn't seem to be in the repos), you may need to point meson to it as such: `meson setup ../build --cmake-prefix-path=/usr/local/lib`

**Comment by oleka2** [comment]
I've never used things like the ghcr.io/aclemons/slackware:15.0 containers.
Maybe the opencascade (zipped) that I compiled myself will help ?
Unpacking it (or only viewing its structure in an archiver) should show where it goes after installation in the system.
I removed some of the biggest files in this zip, because git allows only 25MB as an attachment.
[opencascade-tree-directory.zip](https://github.com/user-attachments/files/16863293/opencascade-tree-directory.zip)

**Comment by carrotIndustries** [comment]
>  should show where it goes after installation in the system.

Based on that I'd try  `--cmake-prefix-path=/usr/lib64`

**Comment by oleka2** [comment]
Not luck as of now, see the screen...
![Screenshot_2024-09-04_11-31-42](https://github.com/user-attachments/assets/c0222960-03e6-455a-88ee-402706bf9654)

**Comment by carrotIndustries** [comment]
Then I'm out of ideas unless I can reproduce it locally.

If you can't build it, you could use the flatpak instead.

**Comment by oleka2** [comment]
This code :
```
cd /usr/lib64/cmake/opencascade
    sed -i -e 's/\\\${OCCT_INSTALL_BIN_LETTER}//' *.cmake
```
resolved the problem, Dune3D compiles well now.

Did you try the VariCAD software ? It maybe interesting.
