### ISSUE TITLE
building on Fedora 40

### ISSUE THREAD

**Issue by AppMathIsRealMath** [dune3d/dune3d#130]
I've really enjoyed HorizonEDA (it's pretty much replaced Kicad for me) and I've started to play with Dune3d - looking good so far!

I recently switched from Ubuntu to Fedora and encountered a build problem with Dune3d (affects HorizonEDA as well) - the opencascade headers are placed in /usr/include/opencascade so the build(s) fail.

A quick hack of meson.build to add that path to the included_directories directive fixed it and all works just fine.

I suppose I should do a pull request but this is a bit simpler... ;-)

**Comment by carrotIndustries** [comment]
> opencascade headers are placed in /usr/include/opencascade so the build(s) fail.

That's strange. Opencascade include paths are discovered via CMake, so the paths should be fine.
