### ISSUE TITLE
Version 1.0 TODOs

### ISSUE THREAD

**Issue by carrotIndustries** [dune3d/dune3d#19]
So I don't forget what should go into version 1.0:

# Packaging
- [x] Install target 
- [x] Desktop file
- [x] Flatpak
- [x] AUR
- [x] Windows ZIPs
- [x] MSI installer

# Documentation

- [x]  Some basic docs on how to use the thing

# Features
## Constraints
 - [x] Perpendicular
 - [x] Angle
 - [x] Parallel

## Groups
 - [x] Rectangular array
 - [ ] (Revolve) Is this really must-have?

## UI
 - [x] Persp/ortho projection
 - [x] Smooth zooming
 - [x] Align camera to workplane
 - [x] Horizontal/vertical tool bar preference
 - [x] Select connected entities action
 - [x] Make default/import export in keys preferences functional
 - [x] Color themes, automatic dark/light
 - [x] Catch exceptions so that it doesn't crash when something goes wrong
 - [x] Test and fix hidpi
 
## Export
 - [x] DXF / SVG export of contours

**Comment by JB63134** [comment]
(Revolve) Is this really must-have?  Absolutely!  Bolt hole patterns on flanges being one example. gear teeth, etc

**Comment by carrotIndustries** [comment]
> Bolt hole patterns on flanges being one example. gear teeth, etc

That's not what revolve does, that's a circular array.

**Comment by carrotIndustries** [comment]
Documentation: https://docs.dune3d.org/en/latest/index.html
