### ISSUE TITLE
Changing the solid model's color requires reloading the project to take effect

### ISSUE THREAD

**Issue by jue89** [dune3d/dune3d#20]
Current HEAD: ed1c07799c100ec8b5bd97a92129f1019cb3383d

What I did:
* Open the Preferences
* Change the `Solid model` color
* See the color not being applied until I reload the project resp. restart Dune3D

**Comment by jue89** [comment]
Looks like it's working now. Maybe 1a29d11cfa555d8ec758a66b3f5b19dd5ae0c472 fixed it?

**Comment by carrotIndustries** [comment]
Yes, that was the intent, forgot to put the issue number in the commit message.
