### ISSUE TITLE
3D mouse support

### ISSUE THREAD

**Issue by thirtythreeforty** [dune3d/dune3d#26]
Please implement support for 3DConnexion input devices.

On Linux, [libspnav](https://github.com/FreeSpacenav/libspnav) can talk to spacenavd.  I am not super familiar with the official 3DxWare SDK on other platforms, but it would provide similar functionality.  An important note, 3DConnexion themselves [contributed the SDK to KiCAD](https://gitlab.com/kicad/code/kicad/-/tree/master/thirdparty/3dxware_sdk) under the GPLv3 so it should be completely compatible to include.

**Comment by thirtythreeforty** [comment]
If you give me some pointers about where this should be integrated, I might be able to take a crack at a libspnav integration.

**Comment by carrotIndustries** [comment]
Good news, the same feature already exists in Horizon EDA and Dune 3D's `Canvas`  is mostly a copy/paste from `Canvas3D` in Horizon EDA. Have a look at https://github.com/horizon-eda/horizon/blob/b78d8063cde1101a56a26562a8206e51e3e45add/src/canvas3d/canvas3d.cpp#L126
