### ISSUE TITLE
Bug: Settings regarding themes are not saved

### ISSUE THREAD

**Issue by jue89** [dune3d/dune3d#30]
1. Open Dune3D
2. Open Perferences
4. Change Variant to anything else than "Auto".
5. Close Preferences 
6. Close Dune3D
7. Reopen Dune3D

Variant changed back to "Auto".

Same goes with Editor -> Dark Theme

(BTW: Haven't understood the difference between selecting Dark theme or changing the Appearance, yet)

**Comment by carrotIndustries** [comment]
Thanks, that must have fallen through the cracks when implementing all of this.

> BTW: Haven't understood the difference between selecting Dark theme or changing the Appearance, yet

Which part in particular? The dark theme in the editor tab is mostly there for windows users where there's no good way to set this system-wide for gtk.
