### ISSUE TITLE
UX: draw contour doesn't create parallel constrain between arc and following line

### ISSUE THREAD

**Issue by jue89** [dune3d/dune3d#35]
Drawing an arc after a line adds the *parallel constrain*. But drawing a line after an arc doesn't. I would like to see this constrain 
being created automatically.

Created constrains:
![Screenshot from 2023-12-08 16-07-53](https://github.com/dune3d/dune3d/assets/6105784/2a0c5be0-8aaf-4679-9a96-e7aa6c0dfe2b)

Expected constrains:
![Screenshot from 2023-12-08 16-09-43](https://github.com/dune3d/dune3d/assets/6105784/4ca93a9a-0dcb-4362-956b-6eb2645d7316)

**Comment by jue89** [comment]
Thanks for addressing this!

Another improvement: Is it possible to add the tangential constrain *after* placing the second point of the following line? That would give more freedom to adjust the angle using the line tool.

**Comment by jue89** [comment]
@carrotIndustries - I don't want to be pushy, but have you seen the comment above?

**Comment by carrotIndustries** [comment]
I don't quite understand how that should work, can you elaborate a bit more?

**Comment by jue89** [comment]
1. click for creating the first point for a line
2. click for creating the second point for the line (the line may get's a horizontal or vertical constrain with that)
3. switch to arc tool
4. click for creating the second point for the arc

Now you're back to the line tool. In the current version (b498e54) it sticks to the tangent of the second point of the arc. That feels cumbersome to me, since I can't be *sloppy* while placing the second point of the arc. Otherwise I have problems creating the line at that point i planned placing it because it's far of the tangent's ray.

I would suggest not to restrict that and allow the user to place the second point of the subsequent line freely. Instead, I would apply the tangent constrain between the arc and second line after the second point of the second line has been places.

Does this make sense?

**Comment by carrotIndustries** [comment]
> I would suggest not to restrict that and allow the user to place the second point of the subsequent line freely.

One can always turn off the tangent constraint by pressing <kbd>t</kbd>.

**Comment by jue89** [comment]
True. But then we're back to the old behavior.

If you intend it to work like this, I rest my case. Just wanted to point out what I think would be a significant improvement for my workflow.

**Comment by carrotIndustries** [comment]
I think now I got what you meant: Moving the end point (top right in this case):
![image](https://github.com/dune3d/dune3d/assets/877304/cacac811-9aef-46f8-83ee-31f0a4a76b8e)
Should move the and point of the arc to keep the current line and the arc tangential.

If I got this right however, this would have one degree of freedom: the length of the line. Should the radius of the arc stay fixed?

**Comment by jue89** [comment]
Thanks for sticking to this conversation :)

> Should the radius of the arc stay fixed?

I'd say yes. I guess that would feel kinda *intuitive*.

**Comment by carrotIndustries** [comment]
> I'd say yes. I guess that would feel kinda intuitive.

Done in the commit above.

**Comment by jue89** [comment]
Wow, this is perfect now! Thank you a lot!
