### ISSUE TITLE
Prior versioning history?

### ISSUE THREAD

**Issue by l29ah** [dune3d/dune3d#5]
I see that you have over 100kSLOC here, do you have any versioning information anywhere prior the "initial import" git commit?

**Comment by carrotIndustries** [comment]
It's only about 24k LOC, the rest are fonts and third-party code.

The history prior to that mostly consists of meaningless `wip` commits since I was more focused on getting things done quickly than having nice commits. Since these have little value, I squashed them all into a single commit.
