### ISSUE TITLE
Exception in signal handler

### ISSUE THREAD

**Issue by blathers123** [dune3d/dune3d#54]
std::exception: map::at

To re-produce:

1. create a new document
2. select sketch and hit the - button to delete it
3. with "reference" selected, hit the triple arrow down button 

Exception shows

Running flatpak version 1.0.0 on Opensuse Tumbleweed

p.s. Might want to make the errors more verbose and have them copy-able 😁

**Comment by ruevs** [comment]
I can confirm the same on Windows.
Self built from https://github.com/dune3d/dune3d/commit/ae9fdb410886c816a9b2ea22ca0549464f10646b (which is version 1.0.0).
