### ISSUE TITLE
Undo issue

### ISSUE THREAD

**Issue by bob-u** [dune3d/dune3d#60]
Open case.d3ddoc
Select first Extrude group of main (for example, all others exhibit the same issue)
Click 'Along normal' to turn it off
Click Undo to revert previous action
Undo is still active and now will cycle 'Along normal' setting every-time it's clicked

In contrast, following works as expected:
Open case.d3ddoc
Select first Extrude group of main
Click 'Along normal' to turn if off
Select last group to select all groups(all check-marks will be blue)
Pressing Undo reverts 'Along normal' change and Undo becomes grayed out.

**Comment by carrotIndustries** [comment]
Should be fixed by c5754a39d08bf343f52ec7e08cdae10938b13abe
