### ISSUE TITLE
The dependency on `mimalloc` can be avoided.

### ISSUE THREAD

**Issue by ruevs** [dune3d/dune3d#7]
The [dependency on `mimalloc`](https://github.com/dune3d/dune3d/blob/5600a99fa2d314f585f6b5e46ee3baa18ad558d8/3rd_party/solvespace/meson.build#L23) for the SolveSpace solver files you are using can be easily avoided (in case you do not want it). Take a look at the last two commits in this branch of mine https://github.com/ruevs/solvespace/commits/Win2k (specifically https://github.com/ruevs/solvespace/commit/f3252418f4c82788b4989848453c691a7346a3eb).

If desired you could simplify the code in platform.cpp even further by leaving only the `#if !defined(WIN32)` section - it compiles and works on Windows just fine. Perhaps it is a tiny bit slower.

P.S. I found Horizon very early and I really like it. I still have not used it for a real project since I very rarely make my own PCBs. With Dune3D you are doing something very interesting! As soon as I find some time to figure out the meson stuff on Windows I will try it and will follow your progress with great interest. I wish you great success in this new adventure :-)

**Comment by carrotIndustries** [comment]
So far, the `mimalloc` dependency doesn't cause any problems, but I'll keep this in mind should it ever become a headache.
