### ISSUE TITLE
Logs window can not be reopened; can lead to crash

### ISSUE THREAD

**Issue by ChrisJohnsen** [dune3d/dune3d#71]
Platform: Windows 10 22H2 19045.3996; 64-bit
Dune 3D: 1.0.0

The Logs window seems like it can not be reopened after it has been closed.

Additionally, I found an action that automatically opens the Logs window: load a file with a null where a number is required (e.g. the "angle" property of an angle constraint). If such a file is loaded after the log window has been opened and closed, Dune 3D crashes.

Incidentally, the "null instead of number" was not hand-edited, it occurred in a normally saved file with a constrained angle applied to parallel lines. I can provide more information about that if anyone is interested. It is maybe an unlikely thing for someone to do, but it can cause a file that needs to be hand-edited to continue using it.

**Comment by carrotIndustries** [comment]
Can you provide some instructions on how to exactly produce the null values?

The problem is that the JSON library I'm using can't round trip NaNs: https://github.com/nlohmann/json/issues/3799

So the best course of action is to prevent the NaNs from getting in there in the first place.
