### ISSUE TITLE
Almost all UI text is missing on Windows 11 in v1.1.0

### ISSUE THREAD

**Issue by RagingRoosevelt** [dune3d/dune3d#97]
OS: Windows 11 build 22631
Dune3d Release: 1.1.0 Beryllium

Steps to reproduce: 
* Download MSI from [release page](https://github.com/dune3d/dune3d/releases/tag/v1.1.0)
* Install using the custom option (only change from defaults was skipping desktop icon)
* Launch

I tried toggling dark theme in preferences to see if that would trigger a redraw (it did, with no resolution to the text issue).

Text shows up in the following places:
* all the tooltips I've seen
* inside the hamburger menu at the top right
* some parts of the settings window

![image](https://github.com/dune3d/dune3d/assets/6985440/7ce1500e-215c-4e8c-bd05-3e246b7f3bac)

![image](https://github.com/dune3d/dune3d/assets/6985440/5cc8c410-8f1d-4bb7-a910-62b8e8bdf625)

![image](https://github.com/dune3d/dune3d/assets/6985440/7817215f-2c81-448b-9590-1226a51d90c7)

Additional notes:

I noticed that, after changing a setting, the contents of `user_config.json` in `%LOCALAPPDATA%\dune3d` was simply `null`, which seemed odd.  I wouldn't rule out that I screwed something up, but I can't think of anything I did (literally installed and launched).

I tried removing and reinstalling using the "typical" option without any change.

**Comment by carrotIndustries** [comment]
> I noticed that, after changing a setting, the contents of user_config.json

That's only used fro the recent files. The preferences are saved to `prefs.json`. 

You could try setting the environment variable `GTK_DEBUG=interactive` and change font to something else in Global→Settings.

Apart from that, the window's header bar also looks a bit off, so there's something else amiss too.

**Comment by carrotIndustries** [comment]
Doesn't seem to be a general problem. Works on a friend's Windows 11 machine.

Is it also broken when building from source: https://docs.dune3d.org/en/latest/build-win32.html

**Comment by RagingRoosevelt** [comment]
> You could try setting the environment variable `GTK_DEBUG=interactive` and change font to something else in Global→Settings.

> Is it also broken when building from source: https://docs.dune3d.org/en/latest/build-win32.html

I'll try to test both when I get home this evening.

**Comment by carrotIndustries** [comment]
> I'll try to test both when I get home this evening.

When you've got MSYS2 installed, you can run `gtk4-demo` to see if it's also broken.

**Comment by RagingRoosevelt** [comment]
OK, I was able to change the debug env var and change the font.  Looks like it worked to change the font but that didn't clear up the issue.
![image](https://github.com/dune3d/dune3d/assets/6985440/092b9ed4-071a-4a01-931b-1da8064dfda6)

**Comment by carrotIndustries** [comment]
The fonts are also broken in the inspector, so this is is Gtk bug.

**Comment by RagingRoosevelt** [comment]
👍SG.  I'll see if there's anything open there already.

**Comment by RagingRoosevelt** [comment]
Tried setting `GSK_RENDERER=cairo` like you mentioned in #121 and that resolved the issue for me
